/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2020-11-12 18:13:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;
import userdata.UserData;
import userdata.UserDataDAO;
import java.util.ArrayList;

public final class bbs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
    _jspx_imports_classes.add("userdata.UserData");
    _jspx_imports_classes.add("userdata.UserDataDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-with\" , initial-scale=\"1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("<title>TODAY LIST 일정관리</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\ta, a:hover{\r\n");
      out.write("\t\tcolor: #000000;\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t}\r\n");
      out.write("\tbody {\r\n");
      out.write("  \t\tbackground-image: url(\"main.jpg\");\r\n");
      out.write("\t}\r\n");
      out.write("\tnav>div>ul>li>a:hover{\r\n");
      out.write("\tfont-weight:900;}\r\n");
      out.write("\t#ajaxTable{\r\n");
      out.write("\t border-top-left-radius: 5px; border-top-right-radius: 5px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//전체보기 페이지\r\n");
      out.write("\r\n");
      out.write(" \t\tvar searchRequest = new XMLHttpRequest();\r\n");
      out.write(" \t\tvar deleteRequest = new XMLHttpRequest();\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\tfunction searchParam(key) {\r\n");
      out.write("\t\t\t  return new URLSearchParams(location.search).get(key);\r\n");
      out.write("\t\t};\t\t \t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write(" \t\tfunction searchFunction(){//search action\r\n");
      out.write(" \t\t\tsearchRequest.open(\"Post\",\"./UserDSearchServlet4?userDate=\" + encodeURIComponent(document.getElementById(\"userDate\").value)+\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t\"&userID=\" + searchParam('userID'), true);\r\n");
      out.write(" \t\t\tsearchRequest.onreadystatechange = searchProcess;\r\n");
      out.write(" \t\t\tsearchRequest.send(null);\r\n");
      out.write(" \t\t}\r\n");
      out.write(" \t\tfunction searchProcess(){ // 각각의 행의 데이터 들을 가지고 오는 과정\r\n");
      out.write(" \t\t\tvar table = document.getElementById(\"ajaxTable\");\r\n");
      out.write(" \t\t\ttable.innerHTML =\"\";\r\n");
      out.write(" \t\t\tif (searchRequest.readyState == 4 && searchRequest.status == 200){\r\n");
      out.write(" \t\t\t\tvar object = eval('(' + searchRequest.responseText + ')');\r\n");
      out.write(" \t\t\t\tvar result = object.result; // 배열을 가져오겠다\t\t\t\r\n");
      out.write(" \t\t\t\tfor(var i = 0; i < result.length; i++) {\r\n");
      out.write(" \t\t\t\t\tvar row = table.insertRow(0);\r\n");
      out.write(" \t\t\t\t\tfor(var j = 0; j < result[i].length; j++){\r\n");
      out.write(" \t\t\t\t\t\tvar cell = row.insertCell(j);\r\n");
      out.write(" \t\t\t\t\t\tcell.innerHTML = result[i][j].value;\r\n");
      out.write(" \t\t\t\t\t}\t\t\t\t\t\r\n");
      out.write(" \t\t\t\t}\t\t\t\r\n");
      out.write(" \t\t\t}\t\t\r\n");
      out.write(" \t\t}\r\n");
      out.write(" \t\twindow.onload = function() {\r\n");
      out.write(" \t\t\tsearchFunction();\t\r\n");
      out.write(" \t\t}\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		 String userID =null;
		if (session.getAttribute("userID") != null){
			userID = (String) session.getAttribute("userID");
		}
		int pageNumber =1;
		if(request.getParameter("pageNumber") != null){			
			pageNumber=Integer.parseInt(request.getParameter("pageNumber"));
		}
	
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-default\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\"\r\n");
      out.write("\t\t\t\taria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<a class =\"navbar-brand\" href=\"Register_main_M2.jsp?userID=");
      out.print(userID );
      out.write("\">TODAY LIST</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t<li ><a href=\"Register_main_M2.jsp?userID=");
      out.print(userID );
      out.write("\">오늘의 일정</a></li>\r\n");
      out.write("\t\t\t\t<li ><a href=\"Register_main_Month.jsp?userID=");
      out.print(userID );
      out.write("\">날짜별 일정</a></li>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"bbs.jsp?userID=");
      out.print(userID );
      out.write("\">전체 일정</a></li>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<li><a href=\"Title_search.jsp?userID=");
      out.print(userID );
      out.write("\">일정 출력</a></li>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t");

				if(userID == null) {
			
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-haspoppup=\"ture\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\">시작하기<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"login.jsp\">로그인</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"join.jsp\">회원가입</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");

				} else {
			
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-haspoppup=\"ture\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\"> ");
      out.print(userID );
      out.write("님 나가기<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"logoutAction.jsp\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
 
				}
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\t\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\t<div  class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"col-md-5 col-md-offset-1\">\r\n");
      out.write("\t\t<table class=\"table\" style=\"text-align: center;  border-radius: 5px; box-shadow: rgba(0,0,0,0.8) 0 0 10px;\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\t\t\t\r\n");
      out.write("\t\t\t<td colspan=\"4\" style=\"background-color: #42579D; align: right;border-top-left-radius: 5px; border-top-right-radius: 5px;\">\r\n");
      out.write("\t\t\t  <div class=\"from-group row pull-right\">\r\n");
      out.write("\t\t\t<div class=\"col-xs-7\">\t\t\t\t\r\n");
      out.write("\t\t\t\t<input class=\"form-control\" onkeyup=\"searchFunction()\" type=\"date\" id=\"userDate\" size=\"20\" placeholder=\"날짜로 찾기\">\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" onclick=\"searchFunction();\" class=\"btn btn-primary\">검색</button>\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-primary\" onClick=\"window.location.reload()\">초기화</button>\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t \t<tr>\t\r\n");
      out.write("\t\t \t\t<th style=\"background-color: #fafafa; text-align: center;\">Title</th>\r\n");
      out.write("\t\t \t\t<th  class=\"col-md-2\" style=\"background-color: #fafafa; text-align: center;\">Date</th>\r\n");
      out.write("\t\t \t\t<th style=\"background-color: #fafafa; text-align: center;\">Memo</th>\r\n");
      out.write("\t\t \t\t<th style=\"background-color: #fafafa; text-align: center;\">Importance</th>\t\t \t\t\r\n");
      out.write("\t\t \t</tr>\t \r\n");
      out.write("\t\t \t</thead>\r\n");
      out.write("\t\t \t<tbody style=\"background-color: #fafafa; text-align: center;\" id=\"ajaxTable\">\t\t\r\n");
      out.write("\t\t \t</tbody>\t \t\r\n");
      out.write("\t\t </table>\r\n");
      out.write("\t\t  </div>\t\r\n");
      out.write("\t\t  <div class=\"col-md-5\">\r\n");
      out.write("\t\t\t<table class=\"table table-striped\" style=\"text-align: center;  border-radius: 5px; box-shadow: rgba(0,0,0,0.8) 0 0 10px;\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr style=\"text-align:right;margin:0px;padding:0px;\">\r\n");
      out.write("\t\t\t\t\t<th colspan=\"4\" style=\"background-color: #42579D; text-align: center;height: 70px;padding-bottom:5px;margin:0px;border-top-left-radius: 5px; border-top-right-radius: 5px;\"><h2><span style=\"color: white;margin:0px;\">TOTAL LIST</span></h2></th></tr>\r\n");
      out.write("\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\tconsole.log(document.getElementsByName(\"userCompletion\").value);\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th  style=\"background-color: #fafafa;  text-align:center;\">Title</th>\r\n");
      out.write("\t\t\t\t\t<th  class=\"col-md-2\" style=\"background-color: #fafafa; text-align:center;\">Date</th>\r\n");
      out.write("\t\t\t\t\t<th  style=\"background-color: #fafafa;  text-align:center;\">Memo</th>\r\n");
      out.write("\t\t\t\t\t<th  style=\"background-color: #fafafa;  text-align:center;\">Importance</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t");

					UserDataDAO userdataDAO = new UserDataDAO();
					ArrayList<UserData> list = userdataDAO.getList(userID);
					for(int i=0;i< list.size(); i++){
				
      out.write("\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"background-color: #fafafa;  text-align:center;\"><a href=\"view_bbs.jsp?bbsID=");
      out.print( list.get(i).getBbsID());
      out.write('"');
      out.write('>');
      out.print( list.get(i).getUserTitle());
      out.write("</a></td> \r\n");
      out.write("\t \t\t\t<td style=\"background-color: #fafafa;  text-align:center;\">");
      out.print(list.get(i).getUserDate());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td style=\"background-color: #fafafa;  text-align:center;\">");
      out.print(list.get(i).getUserMemo());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td style=\"background-color: #fafafa;  text-align:center;\">");
      out.print(list.get(i).getUserCompletion());
      out.write("</td>            \r\n");
      out.write("\t\t\t\t</tr>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t");
 	
					}
				
      out.write("\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a href=\"write_bbs.jsp?userID=");
      out.print(userID);
      out.write("\" style=\"box-shadow: rgba(0,0,0,0.8) 0 0 5px;\"  class=\"btn btn-primary pull-right\">글쓰기</a>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write(" \t<script src= \"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write(" \t<script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
