/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2020-11-12 18:15:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import userdata.UserData;
import userdata.UserDataDAO;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.io.PrintWriter;
import java.util.ArrayList;

public final class Register_005fmain_005fM2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
    _jspx_imports_classes.add("userdata.UserData");
    _jspx_imports_classes.add("userdata.UserDataDAO");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      user.User user = null;
      user = (user.User) _jspx_page_context.getAttribute("user", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (user == null){
        user = new user.User();
        _jspx_page_context.setAttribute("user", user, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("user"), "userID", request.getParameter("userID"), request, "userID", false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("user"), "userPassword", request.getParameter("userPassword"), request, "userPassword", false);
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-with\" , initial-scale=\"1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("<title>TODAY LIST 일정관리</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\ta, a:hover{\r\n");
      out.write("\t\tcolor: #000000;\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t}\r\n");
      out.write("\tbody {\r\n");
      out.write("  \t\tbackground-image: url(\"main.jpg\");\r\n");
      out.write("\t}\r\n");
      out.write("\t#plus{\r\n");
      out.write("\t\theight:173px;\r\n");
      out.write("\t\tpadding:1px 10px 10px 150px;\r\n");
      out.write("background: #E0EAFC;  /* fallback for old browsers */\r\n");
      out.write("background: -webkit-linear-gradient(to right, #CFDEF3, #E0EAFC);  /* Chrome 10-25, Safari 5.1-6 */\r\n");
      out.write("background: linear-gradient(to right, #CFDEF3, #E0EAFC); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */\r\n");
      out.write("\t}\r\n");
      out.write("\tnav>div>ul>li>a:hover{\r\n");
      out.write("\tfont-weight:900;}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" //등록하는 페이지\t\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\tvar registerRequest = new XMLHttpRequest();\t\r\n");
      out.write("\t\tvar search2Request = new XMLHttpRequest();\r\n");
      out.write("\t\t\r\n");
      out.write(" \t\tfunction searchParam(key) {\r\n");
      out.write(" \t\t\t  return new URLSearchParams(location.search).get(key);\r\n");
      out.write(" \t\t};\r\n");
      out.write(" \t\tfunction vCheck(obj, msg)\r\n");
      out.write(" \t\t{\r\n");
      out.write(" \t\t    if (obj.value == \"\" || obj.value == null )\r\n");
      out.write(" \t\t    {\r\n");
      out.write(" \t\t        alert(\"Please Input Your \" + msg) ;\r\n");
      out.write(" \t\t        obj.focus() ;\r\n");
      out.write(" \t\t        return 0 ;\r\n");
      out.write(" \t\t    }\r\n");
      out.write(" \t\t    else\r\n");
      out.write(" \t\t    {\r\n");
      out.write(" \t\t        return 1 ;\r\n");
      out.write(" \t\t    }\r\n");
      out.write(" \t\t}\r\n");
      out.write(" \t\t\t\t\r\n");
      out.write(" \t\tfunction registerFunction(){\t\r\n");
      out.write(" \t\t\tregisterRequest.open(\"Post\",\"./UserDRegisterServlet?userTitle=\" + encodeURIComponent(document.getElementById(\"registerTitle\").value) +\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t\t\"&userDate=\" + encodeURIComponent(document.getElementById(\"registerDate\").value) +\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t\t\"&userMemo=\" + encodeURIComponent(document.getElementById(\"registerMemo\").value) +    \r\n");
      out.write(" \t\t\t\t\t\t\t\t\t\t\"&userCompletion=\" + encodeURIComponent($('input[name=registerCompletion]:checked').val()) +\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t\t\"&userID=\" + searchParam(\"userID\"), true); //이부분 수정 ....\r\n");
      out.write(" \t\t\tregisterRequest.onreadystatechange = registerProcess;\r\n");
      out.write(" \t\t\tregisterRequest.send(null);\r\n");
      out.write(" \t\t\tlocation.href ='Register_main_M1.jsp?userID='+searchParam(\"userID\");\r\n");
      out.write(" \t\t\t\r\n");
      out.write(" \t\t} \t\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\tfunction registerProcess(){\r\n");
      out.write(" \t\t\t if(registerRequest.readyState == 4 && registerRequest.status == 200){\r\n");
      out.write(" \t\t\t\tvar result = registerRequest.responseText; //성공 1 아니면 0\r\n");
      out.write(" \t\t\t\tif(result != 1){\r\n");
      out.write(" \t\t\t\t\talert('등록에 실패했습니다.');\r\n");
      out.write(" \t\t\t\t}\r\n");
      out.write(" \t\t\t\telse{\r\n");
      out.write(" \t\t\t\t\tvar userTitle = document.getElementById(\"userTitle\");\r\n");
      out.write(" \t\t\t\t\tvar registerTitle = document.getElementById(\"registerTitle\");\r\n");
      out.write(" \t\t\t\t\tvar registerDate = document.getElementById(\"registerDate\");\r\n");
      out.write(" \t\t\t\t\tvar registerMemo = document.getElementById(\"registerMemo\");\r\n");
      out.write(" \t\t\t\t\tvar userID = document.getElementById(\"userID\");\r\n");
      out.write(" \t\t\t\t\tuserTitle.value = \"\";\r\n");
      out.write(" \t\t\t\t\tregisterTitle.value = \"\";\r\n");
      out.write(" \t\t\t\t\tregisterDate.value = \"\";\r\n");
      out.write(" \t\t\t\t\tregisterMemo.value = \"\";\r\n");
      out.write(" \t\t\t\t\tuserId.value = \"\";\r\n");
      out.write(" \t\t\t\t\t\r\n");
      out.write(" \t\t\t\t}\r\n");
      out.write(" \t\t\t}\r\n");
      out.write(" \t\t\t\r\n");
      out.write(" \t\t}\t\r\n");
      out.write("\r\n");
      out.write("\t\tfunction getFormatDate(date){\r\n");
      out.write("\t \t\t    var year = date.getFullYear();              //yyyy\r\n");
      out.write("\t \t\t    var month = (1 + date.getMonth());          //M\r\n");
      out.write("\t \t\t    month = month >= 10 ? month : '0' + month;  //month 두자리로 저장\r\n");
      out.write("\t \t\t    var day = date.getDate();                   //d\r\n");
      out.write("\t \t\t    day = day >= 10 ? day : '0' + day;          //day 두자리로 저장\r\n");
      out.write("\t \t\t    return  year + '-' + month + '-' + day;       //'-' 추가하여 yyyy-mm-dd 형태 생성 가능\r\n");
      out.write("\t \t\t};\r\n");
      out.write("\t \t\t\r\n");
      out.write("\t \tfunction searchFunction2(){ \r\n");
      out.write("\t \t\tvar date = new Date();\r\n");
      out.write("\t \t\tdate = getFormatDate(date);\r\n");
      out.write("\t \t\tvar today = date.toString();\r\n");
      out.write("\t \t\t\r\n");
      out.write("\t \t\t\r\n");
      out.write(" \t\t\tsearch2Request.open(\"Post\",\"./UserDSearchServlet2?userDate=\"+today +\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t\t\"&userID=\" + searchParam(\"userID\"), true);\r\n");
      out.write(" \t\t\tsearch2Request.onreadystatechange = searchProcess2;\r\n");
      out.write(" \t\t\tsearch2Request.send(null);\r\n");
      out.write(" \t\t} \t\t\r\n");
      out.write(" \t\tfunction searchProcess2(){ // 각각의 행의 데이터 들을 가지고 오는 과정\r\n");
      out.write(" \t\t\tvar table = document.getElementById(\"ajaxTable\");\r\n");
      out.write(" \t\t\ttable.innerHTML =\"\";\r\n");
      out.write(" \t\t\tif (search2Request.readyState == 4 && search2Request.status == 200){\r\n");
      out.write(" \t\t\t\tvar object = eval('(' + search2Request.responseText + ')');\r\n");
      out.write(" \t\t\t\tvar result = object.result; // 배열을 가져오겠다\t\t\t\r\n");
      out.write(" \t\t\t\tfor(var i = 0; i < result.length; i++) {\r\n");
      out.write(" \t\t\t\t\tvar row = table.insertRow(0);\r\n");
      out.write(" \t\t\t\t\tfor(var j = 0; j < result[i].length; j++){\r\n");
      out.write(" \t\t\t\t\t\tvar cell = row.insertCell(j);\r\n");
      out.write(" \t\t\t\t\t\tcell.innerHTML = result[i][j].value;\r\n");
      out.write(" \t\t\t\t\t}\t\t\t\t\t\r\n");
      out.write(" \t\t\t\t}\t\t\t\r\n");
      out.write(" \t\t\t}\t\t\r\n");
      out.write(" \t\t}\r\n");
      out.write(" \t\twindow.onload = function() {\r\n");
      out.write(" \t\t\t searchFunction2();\t\t\t\r\n");
      out.write(" \t\t}\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		 String userID =null;
		if (session.getAttribute("userID") != null){
			userID = (String) session.getAttribute("userID");
		}		
	
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-default\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\"\r\n");
      out.write("\t\t\t\taria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<a class =\"navbar-brand\" href=\"Register_main_M2.jsp?userID=");
      out.print(userID );
      out.write("\">TODAY LIST</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"Register_main_M2.jsp?userID=");
      out.print(userID );
      out.write("\">오늘의 일정</a></li>\r\n");
      out.write("\t\t\t\t<li ><a href=\"Register_main_Month.jsp?userID=");
      out.print(userID );
      out.write("\">날짜별 일정</a></li>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<li><a href=\"bbs.jsp?userID=");
      out.print(userID );
      out.write("\">전체 일정</a></li>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<li><a href=\"Title_search.jsp?userID=");
      out.print(userID );
      out.write("\">일정 출력</a></li>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t");

				if(userID == null) {
			
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-haspoppup=\"ture\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\">시작하기<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"login.jsp\">로그인</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"join.jsp\">회원가입</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");

				} else {
			
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-haspoppup=\"ture\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\"> ");
      out.print(userID );
      out.write("님 나가기<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"logoutAction.jsp\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
 
				}
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\t\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div  class=\"container-fluid\">\r\n");
      out.write("\t<div id=\"plusOption\" class=\"row\">\r\n");
      out.write("\t<div class=\"col-md-1\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"col-md-10\">\r\n");
      out.write("\t<div id=\"plus\" class=\"jumbotron\" style=\"font-family: 'Nanum Gothic', sans-serif;\">\r\n");
      out.write("    <h2 style=\"font-weight:900;color:black;\">");
      out.print(userID );
      out.write("'s TODAY LIST &nbsp;<span style=\"font-weight:900;color: #42579D;\">오늘도 반갑습니다.</span> </h2> \r\n");
      out.write("    <p style=\"font-size:20px\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"font-size:25px; font-weight:900;background: linear-gradient(to top, #ffe400 50%, transparent 50%);padding:0px 5px 0px 5px;\">TODAY LIST의 일정 변경 방법 설명 </span><br>\r\n");
      out.write("    <span style=\"font-weight:900\"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;오늘의 일정에서 <span style=\"font-weight:900\">TODAY LIST</span>,\r\n");
      out.write("     날짜별 일정에서 <span style=\"font-weight:900\">MONTH LIST</span>, 전체 일정에서 <span style=\"font-weight:900\">TOTAL LIST</span> \r\n");
      out.write("     <br>&nbsp;&nbsp;&nbsp;&nbsp; <span style=\"border-bottom: 1px solid #ffe400; box-shadow: inset 0 -2px 0 #ffe400;padding:0px 3px 0px 3px;\">위 3개의 'LIST'에서 각각 'Title'을 누르시면</span> <span style=\"font-weight:900\">일정의 수정, 삭제, 공유</span>가 가능합니다.</p>\r\n");
      out.write("  \t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"col-md-1\">\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"col-md-5 col-md-offset-1\">\r\n");
      out.write("\t<!--  <div class=\"container\">-->\r\n");
      out.write("\t\t<form method=\"post\" action=\"writeAction_M2.jsp?userID=");
      out.print(userID );
      out.write("\">\r\n");
      out.write("\t\t\t<table class=\"table\" style=\"text-align: center; border-radius: 5px; box-shadow: rgba(0,0,0,0.8) 0 0 10px;\">\r\n");
      out.write("\t\t\t<thead >\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th colspan=\"2\" style=\"background-color: #42579D; text-align:center; color: white; border-top-left-radius: 5px; border-top-right-radius: 5px;\"><h4>일정 등록하기</h4></th>\r\n");
      out.write("\t\t\t\t</tr>\t\t\t\r\n");
      out.write("\t\t\t</thead>\t\t\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t<tr >\r\n");
      out.write("\t\t\t\t\t<td style=\"background-color: #fafafa; text-align: center;\"><h5>Title</h5></td>\r\n");
      out.write("\t\t\t\t\t<td style=\"background-color: #fafafa; text-align: center;\"><input class=\"form-control\" type=\"text\" name=\"userTitle\" size=\"20\" maxlength=\"20\" placeholder=\"(20자 이내)\"></td>\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"background-color: #fafafa; text-align: center;\"><h5>Date</h5></td>\r\n");
      out.write("\t\t\t\t\t<td style=\"background-color: #fafafa; text-align: center;\"><input class=\"form-control\" type=\"date\" name=\"userDate\" size=\"20\"></td>\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"background-color: #fafafa; text-align: center;\"><h5>Memo</h5></td>\r\n");
      out.write("\t\t\t\t\t<td style=\"background-color: #fafafa; text-align: center;\"><input class=\"form-control\" type=\"text\" name=\"userMemo\" size=\"20\" maxlength=\"30\" placeholder=\"(30자 이내)\"></td>\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"background-color: #fafafa; text-align: center; border-bottom-left-radius: 5px;\"><h5>Importance</h5></td>\r\n");
      out.write("\t\t\t\t\t<td style=\"background-color: #fafafa; text-align: center; border-bottom-right-radius:5px;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\" style=\"text-align:center; margin: 0 auto;\">\r\n");
      out.write("\t\t\t\t \t\t\t<div class=\"btn-group\" data-toggle=\"buttons\" >\r\n");
      out.write("\t\t\t\t \t\t\t\t<label class=\"btn btn-primary active\">\r\n");
      out.write("\t\t\t\t \t\t\t\t\t<input type=\"radio\" name=\"userCompletion\" autocomplete=\"off\" value=\"상\" checked>상\r\n");
      out.write("\t\t\t\t \t\t\t\t</label>\r\n");
      out.write("\t\t\t\t \t\t\t\t<label class=\"btn btn-primary\">\r\n");
      out.write("\t\t\t\t \t\t\t\t\t<input type=\"radio\" name=\"userCompletion\" autocomplete=\"off\" value=\"중\" >중\r\n");
      out.write("\t\t\t\t \t\t\t\t</label>\r\n");
      out.write("\t\t\t\t \t\t\t\t<label class=\"btn btn-primary\">\r\n");
      out.write("\t\t\t\t \t\t\t\t\t<input type=\"radio\" name=\"userCompletion\" autocomplete=\"off\" value=\"하\">하\r\n");
      out.write("\t\t\t\t \t\t\t\t\t<!-- 이부분도 수정 -->\r\n");
      out.write("\t\t\t\t \t\t\t\t</label>\t\t\t \t\t\t\t\r\n");
      out.write("\t\t\t\t \t\t\t</div>\r\n");
      out.write("\t\t\t\t \t\t</div>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\t<input type=\"submit\" href=\"write_M2.jsp\" style=\"box-shadow: rgba(0,0,0,0.8) 0 0 3px;\" class=\"btn btn-primary pull-right\" value=\"추가\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<!--  </div>-->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t  <div class=\"col-md-5\">\r\n");
      out.write("\t\t  <table class=\"table table-striped\" style=\"text-align: center; border-radius: 5px; box-shadow: rgba(0,0,0,0.8) 0 0 10px;\">\r\n");
      out.write("\t\t\t\t<thead>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr> \t\t\r\n");
      out.write("\t\t\t \t\t<th colspan=\"3\" style=\"background-color: #42579D; text-align: center; border-top-left-radius: 5px; border-top-right-radius: 5px;\">\r\n");
      out.write("\t\t\t \t\t<h3><button type=\"button\" onclick=\"location.href='Register_main_BT.jsp?userID=");
      out.print(userID );
      out.write("'\" class=\"btn btn-secondary\"><</button>&nbsp;&nbsp;&nbsp;<span style=\"color: white\">TODAY LIST</span>&nbsp;&nbsp;&nbsp;<button type=\"button\" onclick=\"location.href='Register_main_AT.jsp?userID=");
      out.print(userID );
      out.write("'\" class=\"btn btn-secondary\">></button></h3></th>\r\n");
      out.write("\t\t\t \t\t</tr>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<th  style=\"background-color: #fafafa;  text-align:center;\">Title</th>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<th  style=\"background-color: #fafafa;  text-align:center;\">Memo</th>\r\n");
      out.write("\t\t\t\t\t<th  style=\"background-color: #fafafa;  text-align:center;\">Importance</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t");

					Date now = new Date();
					SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd");	
				    String today = sf.format(now);
				    String userDate=today;
					UserDataDAO userdataDAO = new UserDataDAO();
					ArrayList<UserData> list = userdataDAO.getList3(userID,userDate);
					for(int i=0;i< list.size(); i++){
				
      out.write("\t\r\n");
      out.write("\t\t\t\t<tr>\t\t\t\t\r\n");
      out.write("\t\t\t\t<td style=\"background-color: #fafafa; text-align: center; border-bottom-left-radius: 5px; border-top-left-radius: 5px;\"><a href=\"view_M2.jsp?bbsID=");
      out.print( list.get(i).getBbsID());
      out.write('"');
      out.write('>');
      out.print( list.get(i).getUserTitle());
      out.write("</a></td> \t\t\t\t\r\n");
      out.write("\t\t\t\t<td style=\"background-color: #fafafa; text-align: center;\">");
      out.print(list.get(i).getUserMemo());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td style=\"background-color: #fafafa; text-align: center; border-bottom-right-radius:5px; border-top-right-radius: 5px;\">");
      out.print(list.get(i).getUserCompletion());
      out.write("</td>               \r\n");
      out.write("\t\t\t\t</tr>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t");
 	
					}
				
      out.write("\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write(" \t<script src= \"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write(" \t<script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
