/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2020-11-14 16:31:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import user.UserDAO;
import java.io.PrintWriter;

public final class Title_005fsearch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
    _jspx_imports_classes.add("user.UserDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      user.User user = null;
      user = (user.User) _jspx_page_context.getAttribute("user", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (user == null){
        user = new user.User();
        _jspx_page_context.setAttribute("user", user, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("user"), "userID", request.getParameter("userID"), request, "userID", false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("user"), "userPassword", request.getParameter("userPassword"), request, "userPassword", false);
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-with, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("<title>TODAY LIST 일정관리</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\ta, a:hover{\r\n");
      out.write("\t\tcolor: #000000;\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t}\r\n");
      out.write("\tbody {\r\n");
      out.write("  \t\tbackground-image: url(\"main.jpg\");\r\n");
      out.write("\t}\r\n");
      out.write("\tnav>div>ul>li>a:hover{\r\n");
      out.write("\tfont-weight:900;}\r\n");
      out.write("\t#ajaxTable{\r\n");
      out.write("\t border-top-left-radius: 5px; border-top-right-radius: 5px;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable{\r\n");
      out.write("\tmargin:0px; padding:0px\r\n");
      out.write("\t}\r\n");
      out.write("\t@media print {\r\n");
      out.write("  #printPageButton {\r\n");
      out.write("    display: none;\r\n");
      out.write("  }\r\n");
      out.write("  @media print {\r\n");
      out.write("   input[type=text] {\r\n");
      out.write("        display: none;\r\n");
      out.write("    }\r\n");
      out.write("    .btn-group{\r\n");
      out.write("        display: none;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("<script src= \"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"jquery.table2excel.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//전체보기 페이지\r\n");
      out.write("\r\n");
      out.write(" \t\tvar searchRequest = new XMLHttpRequest();\r\n");
      out.write(" \t\tvar deleteRequest = new XMLHttpRequest();\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\tfunction searchParam(key) {\r\n");
      out.write("\t\t\t  return new URLSearchParams(location.search).get(key);\r\n");
      out.write("\t\t};\t\t \t\t\r\n");
      out.write("\t\tfunction printFunction(){\r\n");
      out.write("\t\t\twindow.print();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write(" \t\tfunction searchFunction(){//search action\r\n");
      out.write(" \t\t\tsearchRequest.open(\"Post\",\"./UserDSearchServlet?userTitle=\" + encodeURIComponent(document.getElementById(\"userTitle\").value)+\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t\"&userID=\" + searchParam('userID'), true);\r\n");
      out.write(" \t\t\tsearchRequest.onreadystatechange = searchProcess;\r\n");
      out.write(" \t\t\tsearchRequest.send(null);\r\n");
      out.write(" \t\t}\r\n");
      out.write(" \t\tfunction searchProcess(){ // 각각의 행의 데이터 들을 가지고 오는 과정\r\n");
      out.write(" \t\t\tvar table = document.getElementById(\"ajaxTable\");\r\n");
      out.write(" \t\t\ttable.innerHTML =\"\";\r\n");
      out.write(" \t\t\tif (searchRequest.readyState == 4 && searchRequest.status == 200){\r\n");
      out.write(" \t\t\t\tvar object = eval('(' + searchRequest.responseText + ')');\r\n");
      out.write(" \t\t\t\tvar result = object.result; // 배열을 가져오겠다\t\r\n");
      out.write("\r\n");
      out.write(" \t\t\t\tvar b;\r\n");
      out.write(" \t\t\t\tfor(var i = 0; i < result.length; i ++) {\r\n");
      out.write(" \t\t\t\t\tfor(var j = 0 ; j < result.length-i-1 ; j ++) {\r\n");
      out.write(" \t\t\t\t\t\tvar before = to_date(result[j][1]);\r\n");
      out.write(" \t\t\t\t\t\tvar after = to_date(result[j+1][1]);\r\n");
      out.write("\r\n");
      out.write(" \t\t\t\t\t\tif(before < after) {\r\n");
      out.write(" \t\t\t\t\t\t\tb = result[j];\r\n");
      out.write(" \t\t\t\t\t\t\tresult[j] = result[j+1];\r\n");
      out.write(" \t\t\t\t\t\t\tresult[j+1] = b;\r\n");
      out.write(" \t\t\t\t\t\t}\r\n");
      out.write(" \t\t\t\t\t}\r\n");
      out.write(" \t\t\t\t}\r\n");
      out.write("\r\n");
      out.write(" \t\t\t\tfor(var i = 0; i < result.length; i++) {\r\n");
      out.write(" \t\t\t\t\tvar row = table.insertRow(0);\r\n");
      out.write(" \t\t\t\t\tfor(var j = 0; j < result[i].length; j++){\r\n");
      out.write(" \t\t\t\t\t\tvar cell = row.insertCell(j);\r\n");
      out.write(" \t\t\t\t\t\tcell.innerHTML = result[i][j].value;\r\n");
      out.write(" \t\t\t\t\t}\t\t\t\t\t\r\n");
      out.write(" \t\t\t\t}\t\t\t\r\n");
      out.write(" \t\t\t}\t\t\r\n");
      out.write(" \t\t}\r\n");
      out.write(" \t\twindow.onload = function() {\r\n");
      out.write(" \t\t\tsearchFunction();\t\r\n");
      out.write(" \t\t}\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\tfunction to_date(date_str){\r\n");
      out.write(" \t\t    var yyyyMMdd = String(date_str.value);\r\n");
      out.write(" \t\t    var sYear = yyyyMMdd.substring(0,4);\r\n");
      out.write(" \t\t    var sMonth = yyyyMMdd.substring(5,7);\r\n");
      out.write(" \t\t    var sDate = yyyyMMdd.substring(8,10);\r\n");
      out.write("\r\n");
      out.write(" \t\t    return new Date(Number(sYear), Number(sMonth)-1, Number(sDate));\r\n");
      out.write(" \t\t}\r\n");
      out.write(" \t\tfunction ReportToExcelConverter() { $(\"#TableToExcel\").table2excel({\r\n");
      out.write(" \t\t\texclude: \".noExl\", name: \"Excel Document Name\", filename: searchParam('userID')+\"'s TODAYLIST\" +'.xls', //확장자를 여기서 붙여줘야한다.\r\n");
      out.write(" \t\t\tfileext: \".xls\", exclude_img: true, exclude_links: true, exclude_inputs: true }); }\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		 String userID =null;
		if (session.getAttribute("userID") != null){
			userID = (String) session.getAttribute("userID");
		}
	
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-default\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\"\r\n");
      out.write("\t\t\t\taria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<a class =\"navbar-brand\" href=\"Register_main_M2.jsp?userID=");
      out.print(userID );
      out.write("\">TODAY LIST</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t<li ><a href=\"Register_main_M2.jsp?userID=");
      out.print(userID );
      out.write("\">오늘의 일정</a></li>\r\n");
      out.write("\t\t\t\t<li ><a href=\"Register_main_Month.jsp?userID=");
      out.print(userID );
      out.write("\">날짜별 일정</a></li>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<li><a href=\"bbs.jsp?userID=");
      out.print(userID );
      out.write("\">전체 일정</a></li>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"Title_search.jsp?userID=");
      out.print(userID );
      out.write("\">일정 출력</a></li>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t");

				if(userID == null) {
			
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-haspoppup=\"ture\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\">시작하기<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"login.jsp\">로그인</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"join.jsp\">회원가입</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");

				} else {
			
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a href=\"logoutAction.jsp\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-haspoppup=\"ture\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\"> ");
      out.print(userID );
      out.write("님 나가기<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"logoutAction.jsp\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
 
				}
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\t\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t<div class=\"row\" style=\"text-align: center; margin: 0 auto; line-height:50px; border-radius: 5px; box-shadow: rgba(0,0,0,0.8) 0 0 10px; height:50px; background-color: #42579D;\">\r\n");
      out.write("\t\t\t<div class=\"col-xs-4 col-md-pull-0\">\r\n");
      out.write("\t\t\t<div class=\"form-group\" style=\"text-align:center; margin: 0 auto;\">\r\n");
      out.write("\t\t\t<div class=\"btn-group\" data-toggle=\"buttons\">\r\n");
      out.write("\t\t\t\t \t\t<label class=\"btn btn-primary\">\r\n");
      out.write("\t\t\t\t \t\t\t<input type=\"radio\" onclick=\"printFunction();\">Print\r\n");
      out.write("\t\t\t\t \t\t</label>\r\n");
      out.write("\t\t\t\t \t\t<label class=\"btn btn-primary\">\r\n");
      out.write("\t\t\t\t \t\t\t<input type=\"radio\"  onclick=\"ReportToExcelConverter()\" >Excel\r\n");
      out.write("\t\t\t\t \t\t</label>\t\t\t\t \t\t\t\t\t \t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"from-group row pull-right\">\r\n");
      out.write("\t\t\t<div class=\"col-xs-7\" style=\"line-height:50px;padding-top:9px\">\r\n");
      out.write("\t\t\t\t<input class=\"form-control\" id=\"userTitle\" onkeyup=\"searchFunction()\" type=\"text\" size=\"40\" placeholder=\"Title로 따로보기\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-xs-1\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" id=\"printPageButton\" onclick=\"searchFunction();\" class=\"btn btn-primary\">검색</button>\r\n");
      out.write("\t\t\t</div>\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t </div>\r\n");
      out.write("\t\t \t<table id=\"TableToExcel\" class=\"table\" style=\"text-align: center; border-radius: 5px; box-shadow: rgba(0,0,0,0.8) 0 0 10px;\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t \t<tr>\r\n");
      out.write("\t\t \t\t<th style=\"background-color: #fafafa; text-align: center;\">Title</th>\r\n");
      out.write("\t\t \t\t<th style=\"background-color: #fafafa; text-align: center;\">Date</th>\r\n");
      out.write("\t\t \t\t<th style=\"background-color: #fafafa; text-align: center;\">Memo</th>\r\n");
      out.write("\t\t \t\t<th style=\"background-color: #fafafa; text-align: center;\">Importance</th>\t\t \t\t\r\n");
      out.write("\t\t \t</tr>\t \r\n");
      out.write("\t\t \t</thead>\r\n");
      out.write("\t\t \t<tbody style=\"background-color: #fafafa; text-align: center;\" id=\"ajaxTable\">\t\t\r\n");
      out.write("\t\t \t</tbody>\t \t\r\n");
      out.write("\t\t \t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
