/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2020-11-12 18:53:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;
import userdata.UserData;
import userdata.UserDataDAO;

public final class update_005fbbs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
    _jspx_imports_classes.add("userdata.UserData");
    _jspx_imports_classes.add("userdata.UserDataDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-with\" , initial-scale=\"1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("<title>TODAY LIST 일정관리</title>\r\n");
      out.write("<style>\r\n");
      out.write(".container {\r\n");
      out.write("  width: 50%;\r\n");
      out.write("}\r\n");
      out.write("body {\r\n");
      out.write("  \t\tbackground-image: url(\"ect.jpg\");\r\n");
      out.write("\t}\r\n");
      out.write("\tnav>div>ul>li>a:hover{\r\n");
      out.write("\tfont-weight:900;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		String userID =null;
		if (session.getAttribute("userID") != null){
			userID = (String) session.getAttribute("userID");
		}
		if(userID == null){
			PrintWriter script =response.getWriter();
			script.println("<script>");
			script.println("alert('로그인을 하세요.')");
			script.println("location.href ='login.jsp'");
			script.println("</script>");
		}		
		int bbsID = 0;
		if(request.getParameter("bbsID") != null){
			bbsID = Integer.parseInt(request.getParameter("bbsID"));	
		}
		if(bbsID == 0){
			PrintWriter script =response.getWriter();
			script.println("<script>");
			script.println("alert('유효하지 않은 글입니다.')");
			script.println("location.href ='bbs.jsp'");
			script.println("</script>");
		}
		UserData bbs =new UserDataDAO().getBbs(bbsID);
		if(!userID.equals(bbs.getUserID())){
			PrintWriter script =response.getWriter();
			script.println("<script>");
			script.println("alert('권한이 없습니다.')");
			script.println("location.href ='bbs.jsp'");
			script.println("</script>");
		}
	
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-default\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\"\r\n");
      out.write("\t\t\t\taria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<a class =\"navbar-brand\">TODAY LIST</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t<li ><a href=\"Register_main_M2.jsp?userID=");
      out.print(userID );
      out.write("\">오늘의 일정</a></li>\r\n");
      out.write("\t\t\t\t<li ><a href=\"Register_main_Month.jsp?userID=");
      out.print(userID );
      out.write("\">날짜별 일정</a></li>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"bbs.jsp?userID=");
      out.print(userID );
      out.write("\">일정 변경</a></li>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<li><a href=\"Title_search.jsp?userID=");
      out.print(userID );
      out.write("\">일정 출력</a></li>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-haspoppup=\"ture\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\">");
      out.print(userID );
      out.write("님 나가기<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"logoutAction.jsp\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\t\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t<form method=\"post\" action=\"updateAction_bbs.jsp?bbsID=");
      out.print(bbsID);
      out.write("\">\r\n");
      out.write("\t\t\t<table class=\"table\" style=\"text-align: center;  border-radius: 5px; box-shadow: rgba(0,0,0,0.8) 0 0 10px;\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th colspan=\"2\" style=\"background-color: #42579D; text-align:center; color: white; border-top-left-radius: 5px; border-top-right-radius: 5px;\"><h4>일정 수정하기</h4></th>\r\n");
      out.write("\t\t\t\t</tr>\t\t\t\r\n");
      out.write("\t\t\t</thead>\t\t\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"background-color: #fafafa; text-align: center;\"><h5>Title</h5></td>\r\n");
      out.write("\t\t\t\t\t<td style=\"background-color: #fafafa; text-align: center;\"><input class=\"form-control\" type=\"text\" name=\"userTitle\" size=\"20\" maxlength=\"20\"  value=\"");
      out.print( bbs.getUserTitle());
      out.write("\"></td>\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"background-color: #fafafa; text-align: center;\"><h5>Date</h5></td>\r\n");
      out.write("\t\t\t\t\t<td style=\"background-color: #fafafa; text-align: center;\"><input class=\"form-control\" type=\"date\" name=\"userDate\" size=\"20\" value=\"");
      out.print( bbs.getUserDate());
      out.write("\"></td>\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"background-color: #fafafa; text-align: center;\"><h5>Memo</h5></td>\r\n");
      out.write("\t\t\t\t\t<td style=\"background-color: #fafafa; text-align: center;\"><input class=\"form-control\" type=\"text\" name=\"userMemo\" size=\"20\" maxlength=\"30\"  value=\"");
      out.print( bbs.getUserMemo() );
      out.write("\"></td>\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"background-color: #fafafa; text-align: center;border-bottom-left-radius: 5px;\"> <h5>Importance</h5></td>\r\n");
      out.write("\t\t\t\t\t<td style=\"background-color: #fafafa; text-align: center;border-bottom-right-radius:5px;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\" style=\"text-align:center; margin: 0 auto;\">\r\n");
      out.write("\t\t\t\t \t\t\t<div class=\"btn-group\" data-toggle=\"buttons\">\r\n");
      out.write("\t\t\t\t \t\t\t\t<label class=\"btn btn-primary active\">\r\n");
      out.write("\t\t\t\t \t\t\t\t\t<input type=\"radio\" name=\"userCompletion\" autocomplete=\"off\" value=\"상\" >상\r\n");
      out.write("\t\t\t\t \t\t\t\t</label>\r\n");
      out.write("\t\t\t\t \t\t\t\t<label class=\"btn btn-primary\">\r\n");
      out.write("\t\t\t\t \t\t\t\t\t<input type=\"radio\" name=\"userCompletion\" autocomplete=\"off\" value=\"중\" >중\r\n");
      out.write("\t\t\t\t \t\t\t\t</label>\r\n");
      out.write("\t\t\t\t \t\t\t\t<label class=\"btn btn-primary\">\r\n");
      out.write("\t\t\t\t \t\t\t\t\t<input type=\"radio\" name=\"userCompletion\" autocomplete=\"off\" value=\"하\">하\r\n");
      out.write("\t\t\t\t \t\t\t\t\t<!-- 이부분도 수정 -->\r\n");
      out.write("\t\t\t\t \t\t\t\t</label>\t\t\t \t\t\t\t\r\n");
      out.write("\t\t\t\t \t\t\t</div>\r\n");
      out.write("\t\t\t\t \t\t</div>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</td>\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\t<a href=\"bbs.jsp?userID=");
      out.print(userID );
      out.write("\" class=\"btn btn-primary\" style=\"box-shadow: rgba(0,0,0,0.8) 0 0 3px;\">목록</a>\r\n");
      out.write("\t\t\t<input type=\"submit\" class=\"btn btn-primary pull-right\" style=\"box-shadow: rgba(0,0,0,0.8) 0 0 3px;\" value=\"글수정\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write(" \t<script src= \"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write(" \t<script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
